version: "3.8"
services:
    karate-tests:
      image: karate-tests
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./target:/usr/src/app/target
        - ~/.m2:/root/.m2
      commad: mvn test

#command to execute: docker-compose up --build